insert into public.programs (program_course_code_ref, program_course_rev_ref, program_assignment)
values  ('SE_ADV_DB', 2, 'SE'),
        ('SE_ADV_JAVA', 2, 'SE'),
        ('SE_ADV_JS', 3, 'SE'),
        ('PM_AGILE', 2, 'ISM'),
        ('AI_DATA_PREP', 1, 'AIs'),
        ('AI_DATA_SCIENCE_IN_PROD', 1, 'AIs'),
        ('AI_DATA_SCIENCE_IN_PROD', 1, 'DSA'),
        ('CS_DATA_PRIV', 1, 'CS'),
        ('CS_SOFTWARE_SECURITY', 1, 'CS'),
        ('MK_COM_FOR_LEADER', 1, 'ISM'),
        ('DT_RDBMS', 3, 'ISM'),
        ('DT_RDBMS', 3, 'SE'),
        ('DT_RDBMS', 3, 'CS'),
        ('DT_RDBMS', 3, 'DSA'),
        ('DT_RDBMS', 3, 'AIs'),
        ('PG_PYTHON', 2, 'ISM'),
        ('PG_PYTHON', 2, 'SE'),
        ('PG_PYTHON', 2, 'CS'),
        ('PG_PYTHON', 2, 'DSA'),
        ('PG_PYTHON', 2, 'AIs');