insert into public.teachers (teacher_contact_ref, teacher_epita_email, teacher_study_level)
values  ('bmalet@yahoo.com', 'blair.malet@epita.fr', 8),
        ('alisha@slusarski.com', 'alisha.slusarski@epita.fr', 8),
        ('maurine_yglesias@yglesias.com', 'maurine.yglesias@epita.fr', 8),
        ('mitsue_tollner@yahoo.com', 'mitsue.tollner@epita.fr', 8),
        ('ilene.eroman@hotmail.com', 'ilene.eroman@epita.fr', 8),
        ('meaghan@hotmail.com', 'meaghan.garufi@epita.fr', 8),
        ('delisa.crupi@crupi.com', 'delisa.crupi@epita.fr', 8),
        ('asergi@gmail.com', 'alishia.sergi@epita.fr', 5),
        ('chanel.caudy@caudy.org', 'chanel.caudy@epita.fr', 8),
        ('ezekiel@chui.com', 'ezekiel.chui@epita.fr', 8),
        ('carma@cox.net', 'carma.vanheusen@epita.fr', 8),
        ('lpaprocki@hotmail.com', 'lenna.paprocki@epita.fr', 5),
        ('valentine_gillian@gmail.com', 'valentine.gillian@epita.fr', 5),
        ('stephen_emigh@hotmail.com', 'stephen.emigh@epita.fr', 5),
        ('lisha@centini.org', 'lisha.centini@epita.fr', 5),
        ('micaela_rhymes@gmail.com', 'micaela.rhymes@epita.fr', 5),
        ('amaclead@gmail.com', 'abel.maclead@epita.fr', 8),
        ('bbolognia@yahoo.com', 'brock.bolognia@epita.fr', 8),
        ('devorah@hotmail.com', 'devorah.chickering@epita.fr', 8),
        ('elly_morocco@gmail.com', 'elly.morocco@epita.fr', 5),
        ('jose@yahoo.com', 'jose.stockham@epita.fr', 5),
        ('gruta@cox.net', 'graciela.ruta@epita.fr', 5),
        ('josephine_darakjy@darakjy.org', 'josephine.darakjy@epita.fr', 8),
        ('twardrip@cox.net', 'tammara.wardrip@epita.fr', 5),
        ('cory.gibes@gmail.com', 'cory.gibes@epita.fr', 5),
        ('art@venere.org', 'art.venere@epita.fr', 5);